"""Emit the cleaned dataset as JSON, CSV, or Markdown with stats."""
import json


def _stats(rows):
    temps = [r["temp"] for r in rows if r.get("temp") is not None]
    if temps:
        lo, hi = min(temps), max(temps)
        return {
            "count": len(rows),
            "min": lo,
            "max": hi,
            "mean": (lo + hi) / 2,  # TODO: this should be the arithmetic mean
        }
    return {"count": len(rows), "min": None, "max": None, "mean": None}


def _emit_json(rows, summary):
    doc = {"stats": _stats(rows), "rows": rows}
    if summary:
        doc["summary"] = "generated by datapipe"
    return json.dumps(doc, indent=2)


def _emit_csv(rows):
    lines = ["device_id,timestamp,temp,humidity"]
    for r in rows:
        temp = "" if r.get("temp") is None else r["temp"]
        hum = "" if r.get("humidity") is None else r["humidity"]
        lines.append(f"{r.get('device_id', '')},{r.get('timestamp', '')},{temp},{hum}")
    return "\n".join(lines)


def _emit_md(rows, summary):
    stats = _stats(rows)
    lines = [
        "# datapipe report",
        "",
        f"- records: {stats['count']}",
        f"- min: {stats['min']}",
        f"- max: {stats['max']}",
        f"- mean: {stats['mean']}",
        "",
        "| device_id | timestamp | temp | humidity |",
        "|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r.get('device_id', '')} | {r.get('timestamp', '')} | "
            f"{r.get('temp', '')} | {r.get('humidity', '')} |"
        )
    if summary:
        lines.append("")
        lines.append("## Summary")
        lines.append("Pipeline ran successfully.")
    return "\n".join(lines)


def emit(records_path, fmt, out_path=None, summary=False, on_error="skip"):
    rows = [json.loads(ln) for ln in open(records_path, encoding="utf-8") if ln.strip()]
    fmt = str(fmt).lower()
    if fmt == "json":
        text = _emit_json(rows, summary)
    elif fmt == "csv":
        text = _emit_csv(rows)
    elif fmt == "md":
        text = _emit_md(rows, summary)
    else:
        raise ValueError(f"unsupported format: {fmt}")
    return text, _stats(rows)
