"""Emit the cleaned dataset as JSON, CSV, or Markdown with stats.

v2.4: honors `on_error`. In "fail" mode the first malformed record raises
DataError and `out_path` is never created or modified (atomic write).
"""
import csv
import io
import json

from ._atomic import atomic_write_text
from .errors import DataError


def _stats(rows):
    temps = [r["temp"] for r in rows if r.get("temp") is not None]
    if temps:
        return {
            "count": len(rows),
            "min": min(temps),
            "max": max(temps),
            "mean": sum(temps) / len(temps),
        }
    return {"count": len(rows), "min": None, "max": None, "mean": None}


def _emit_json(rows, summary):
    doc = {"stats": _stats(rows), "rows": rows}
    if summary:
        doc["summary"] = "generated by datapipe"
    return json.dumps(doc, indent=2)


def _emit_csv(rows):
    header = ["device_id", "timestamp", "temp", "humidity"]
    buf = io.StringIO()
    writer = csv.writer(buf, lineterminator="\n")
    writer.writerow(header)
    for r in rows:
        writer.writerow([
            r.get("device_id", ""),
            r.get("timestamp", ""),
            "" if r.get("temp") is None else r["temp"],
            "" if r.get("humidity") is None else r["humidity"],
        ])
    return buf.getvalue().rstrip("\n")


def _emit_md(rows, summary):
    stats = _stats(rows)
    lines = [
        "# datapipe report",
        "",
        f"- records: {stats['count']}",
        f"- min: {stats['min']}",
        f"- max: {stats['max']}",
        f"- mean: {stats['mean']}",
        "",
        "| device_id | timestamp | temp | humidity |",
        "|---|---|---|---|",
    ]
    def esc(v):
        return str(v).replace("|", "\\|").replace("\n", " ")
    for r in rows:
        lines.append(
            f"| {esc(r.get('device_id', ''))} | {esc(r.get('timestamp', ''))} | "
            f"{esc(r.get('temp', ''))} | {esc(r.get('humidity', ''))} |"
        )
    if summary:
        lines.append("")
        lines.append("## Summary")
        lines.append("Pipeline ran successfully.")
    return "\n".join(lines)


def _load_rows(records_path, on_error):
    rows = []
    with open(records_path, "r", encoding="utf-8") as fh:
        for ln in fh:
            if not ln.strip():
                continue
            try:
                rows.append(json.loads(ln))
            except json.JSONDecodeError:
                if on_error == "fail":
                    raise DataError("malformed record in input") from None
                continue
    return rows


def emit(records_path, fmt, out_path=None, summary=False, on_error="skip"):
    rows = _load_rows(records_path, on_error)
    fmt = str(fmt).lower()
    if fmt == "json":
        text = _emit_json(rows, summary)
    elif fmt == "csv":
        text = _emit_csv(rows)
    elif fmt == "md":
        text = _emit_md(rows, summary)
    else:
        raise ValueError(f"unsupported format: {fmt}")
    if out_path:
        atomic_write_text(out_path, text)
    return text, _stats(rows)
